Vagrant.configure("2") do |config|
  config.vm.hostname = "java01"
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.3"

  config.vm.provision "shell", path:"../provision.sh"

end
